name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:1.24

    services:
      redis6:
        image: redis:6.2-alpine
        ports:
          - 6362:6379
      redis7:
        image: redis:7.4-alpine
        ports:
          - 6374:6379
      valkey8:
        image: valkey/valkey:8.0-alpine
        ports:
          - 6380:6379

    strategy:
      matrix:
        redis-host: [redis6, redis7, valkey8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      env:
        REDIS_HOST: ${{ matrix.redis-host }}
      run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
