name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379

    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run tests
      run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
