name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:1.24

    services:
      valkey7:
        image: valkey/valkey:7.2-alpine
        ports:
          - 6372:6379
      valkey8:
        image: valkey/valkey:8.0-alpine
        ports:
          - 6380:6379

    strategy:
      matrix:
        valkey-host: [valkey7, valkey8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      env:
        VALKEY_HOST: ${{ matrix.valkey-host }}
      run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
